-- CREATE TABLE users (id INTEGER NOT NULL PRIMARY KEY, username TEXT NOT NULL, password TEXT NOT NULL);
-- INSERT INTO users (username, password) VALUES ("loco", "1234");
-- SELECT * FROM users;
-- .schema